/**
 * Query barrel export
 * Re-exports all domain query modules for centralized access
 */
export { queryKeys } from './keys'
export { useCurrentUser, useLogin, useRegister, useLogout } from './auth'
export {
  useLogs,
  useStats,
  useClearLogs,
  useDeleteLog,
  useBatchStatus,
  usePauseBatch,
  useResumeBatch,
  useCancelBatch,
  useScheduledJobs,
  useCancelScheduledJob,
  useQueueJobs,
  useQueueStats,
  usePauseJob,
  useResumeJob,
  useCancelJob,
} from './email'
export {
  useContactLists,
  useCreateContactList,
  useUpdateContactList,
  useDeleteContactList,
  useContacts,
  useAddContact,
  useUpdateContact,
  useBulkDeleteContacts,
  useBulkTagContacts,
  useBulkMoveContacts,
  useImportContacts,
  useImportHistory,
  useValidateEmails,
  useValidateSingleEmail,
} from './contacts'
export {
  useConfigs,
  useCreateConfig,
  useUpdateConfig,
  useDeleteConfig,
  useTestConfig,
  useTestConnection,
  useOAuthStatus,
  useConnectOAuth,
  useDisconnectOAuth,
  useTestOAuth,
} from './config'
export {
  useTemplates,
  useTemplate,
  useStarterTemplates,
  useCreateTemplate,
  useUpdateTemplate,
  useDeleteTemplate,
  useDuplicateTemplate,
} from './templates'
export {
  useCampaigns,
  useCampaign,
  useCreateCampaign,
  useUpdateCampaign,
  useDeleteCampaign,
  useLaunchCampaign,
  useCloneCampaign,
  usePauseCampaign,
  useCancelCampaign,
  useArchiveCampaign,
  useCampaignStats,
  useAutomations,
  useAutomation,
  useCreateAutomation,
  useDeleteAutomation,
} from './campaigns'
export {
  useDashboardStats,
  usePollStatus,
  useRoutingScores,
  useRoutingDashboard,
  useRoutingConfig,
  useUpdateRoutingConfig,
  useWarmupPlans,
  useWarmupPlan,
  useWarmupProgress,
  useCreateWarmup,
  usePauseWarmup,
  useResumeWarmup,
  useCancelWarmup,
  useAnalyticsSummary,
  useAnalyticsReports,
  useCampaignAnalytics,
  useDeviceAnalytics,
  useTimeAnalysis,
  usePlugins,
  useAvailableProviders,
  useInstallPlugin,
  useActivatePlugin,
  useDisablePlugin,
  useUninstallPlugin,
} from './dashboard'
