// Drizzle (Postgres) schema barrel. Domains added per P2 sub-stage.
export * from './identity'
export * from './contacts'
export * from './campaigns'
export * from './templates'
export * from './queue'
export * from './automations'
export * from './deliverability'
export * from './integrations'
export * from './misc'
export * from './logs'
